# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Official Blockchain Haters Club
email: obhc.nft@gmail.com
description: |
  The Official Blockchain Haters Club (O.B.H.C.) is a limited collection of 
  500 unique NFTs on the Solana network, including some of the best and most 
  critical statements and questions from haters. This collection is inspired 
  from all of the negative and hateful opinions about blockchain, crypto, NFT’s, 
  and the decentralization space as a whole.

  We truly believe that blockchain technology, along with what it enables, is 
  the technology of the future. NFT's are inherently more valuable than people 
  think, and we want to prove that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "obhc.github.io/OBHC.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OBHC_NFT

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
